---
launch_config_version: 1
deployment_name: acs-test-test-123
provider: acs-engine
key_helper: true
num_masters: 1
num_windows_public_agents: 1
num_windows_private_agents: 1
num_linux_public_agents: 1
num_linux_private_agents: 1
azure_location: East US 2
tags:
    expiration: 4h
    owner: '@mellenburg'
